---
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
    - "bundle exec rake validate metadata_lint lint spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    dist: trusty
    env: BEAKER_set=centos-7 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    bundler_args: --without system_tests
    env: STRICT_VARIABLES="yes"
    script: bundle exec rake rubocop
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
  - rvm: 2.4.0
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes DEPLOY_TO_FORGE=yes
deploy:
  provider: puppetforge
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
notifications:
  email: false
